name: LauraJaramillo
favicon: null
layout_spectrum: 0.7577734908554703
typography_spectrum: 0.9206799624953419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.22874169959686697
  lightness: 0.4080310482531786
  saturation: 0.35450685140676796
  rhythmicContrast: 0.011615534080192447
purpose: []
